import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Footer, Navbar} from "@/components/Data";
import {ReactNode} from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cars Showcasing',
  description: 'Generated by mmounib',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative">
      <Navbar />
      {children}
      <Footer />
      </body>
    </html>
  )
}
